version: '3'

secrets:
  konga_source:
    file: ./secrets/source.js
  konga_user:
    file: ./secrets/user.js


x-kong-config:
  &kong-env
  KONG_DATABASE: postgres
  KONG_PG_DATABASE: kong
  KONG_PG_HOST: kong-database
  KONG_PG_USER: ${POSTGRES_USER}
  KONG_PG_PASSWORD: ${POSTGRES_PASSWORD}

services:

  kong-database:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: kong
    ports:
      - "15432:5432"
    volumes:
      - ./data/kong-database:/var/lib/postgresql/data

  kong-migrations:
    image: kong:latest
    command: kong migrations bootstrap
    depends_on:
      - kong-database
    environment:
      <<: *kong-env
    restart: on-failure

  kong-migrations-up:
    image: kong:latest
    command: kong migrations up && kong migrations finish
    depends_on:
      - kong-database
    environment:
      <<: *kong-env
    restart: on-failure

  kong:
    image: kong:latest
    restart: always
    environment:
      <<: *kong-env
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    volumes:
      - ./kong.yml:/usr/local/kong/kong.yml
    ports:
      - "8000:8000" # Kong Proxy Port
      - "8443:8443" # Kong Proxy SSL Port
      - "8001:8001" # Kong Admin API Port
      - "8444:8444" # Kong Admin API SSL Port
    depends_on:
      - kong-database

  deck:
    image: kong/deck:latest
    volumes:
      - ./secrets/kong.yml:/kong.yml
      - ./secrets/deck.yml:/deck.yml
    restart: on-failure
    entrypoint: ["deck", "gateway", "sync", "/kong.yml", "--config", "/deck.yml"]
    depends_on:
      - kong

  konga:
    image: pantsel/konga:latest
    container_name: konga
    restart: on-failure
    secrets:
      - konga_source
      - konga_user
    environment:
      NODE_ENV: production
      KONGA_HOOK_TIMEOUT: 120000
      KONGA_SEED_USER_DATA_SOURCE_FILE: /run/secrets/konga_user
      KONGA_SEED_KONG_NODE_DATA_SOURCE_FILE: /run/secrets/konga_source
    ports:
      - "1337:1337"

      
